name: Android CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2  # Upgrade to v3 if available

    - name: Set up JDK
      uses: actions/setup-java@v2  # Assuming v2 is the updated version
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
